stages:
  - test
  - deploy

variables:
  GOPATH: $CI_PROJECT_DIR/.go

cache:
  paths:
    - .go/pkg/mod/

unit_tests:
  stage: test
  image: golang:1.25-alpine
  before_script:
    - apk add --no-cache git build-base
  script:
    - go test -v -short ./...

deploy_to_fly:
  stage: deploy
  image: alpine:3.19
  only:
    - main
  before_script:
    - apk add --no-cache curl bash
    - curl -L https://fly.io/install.sh | sh
    - export FLYCTL_INSTALL="/root/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"
  script:
    - echo "Token length: ${#FLY_API_TOKEN}"
    - flyctl deploy --remote-only
