version: "3.9"

services:
  app:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/Dockerfile
    container_name: music-app
    env_file:
      - ${PROJECT_ROOT}/.env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - LOGGER_FOLDER=/app/out/logs
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: music-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: music-redis
    volumes:
      - ${PROJECT_ROOT}/out/redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: music-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:postgres:5432
    ports:
      - "127.0.0.1:5432:5432"

  redis-port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: music-redis-port-forwarder
    command: tcp-listen:6379,fork,reuseaddr tcp-connect:redis:6379
    ports:
      - "127.0.0.1:6379:6379"

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  swagger:
    build:
      context: ${PROJECT_ROOT}
      dockerfile_inline: |
        FROM golang:alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - ${PROJECT_ROOT}:/code
